version: '3.8'
services:
  spring-application:
    container_name: spring-application
    image: ${DOCKER_USER_NAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    restart: on-failure
    ports:
      - ${SPRING_OUTER_PORT}:${SPRING_INNER_PORT}
    depends_on:
      - mysql-db
    networks:
      - internal-network
      - external-network
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - internal-network
networks:
  external-network:
    driver: bridge
    internal: false
  internal-network:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
          - subnet: ${INTERNAL_NETWORK_SUBNET}
            ip_range: ${INTERNAL_NETWORK_IP_RANGE}
            gateway: ${INTERNAL_NETWORK_GATEWAY}
            aux_addresses:
              mysql-db: ${INTERNAL_NETWORK_AUX_ADDRESS_MYSQL}
              spring-application: ${INTERNAL_NETWORK_AUX_ADDRESS_SPRING_APPLICATION}