services:
  spring-application:
    container_name: spring-application
    image: ${DOCKER_USER_NAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    restart: on-failure
    ports:
      - ${SPRING_OUTER_PORT}:${SPRING_INNER_PORT}
    depends_on:
      - mysql-db
    networks:
      - docker-network
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_OUTER_PORT}:${MYSQL_INNER_PORT}
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge