services:
  spring-application:
    container_name: spring-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306